# Используем официальный образ Python
FROM python:3.9

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY . /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r /app/stocks_products/requirements.txt

# Устанавливаем переменные окружения
ENV DJANGO_SETTINGS_MODULE=stocks_products.settings
ENV PYTHONUNBUFFERED=1

# Открываем порт 8000 для доступа
EXPOSE 8000

# Выполняем миграции и запускаем сервер Django
CMD ["sh", "-c", "cd /app/stocks_products && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
